version: "3.8"

services:
  shoppingdb:
    container_name: shoppingdb-container
    image: postgres
    environment:
      POSTGRES_USER: hse24
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shoppingdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hse24"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5000:8080"
    environment:
      DB_HOST: shoppingdb
      DB_PORT: 5432
      DB_USER: hse24
      DB_PASSWORD: password
      DB_NAME: shoppingdb
    depends_on:
      shoppingdb:
        condition: service_healthy

  frontend-react:
    build:
      context: ./frontend-react        # <--- Neuer Pfad zu deinem React-Frontend
      dockerfile: Dockerfile
    container_name: frontend-container-react
    ports:
      - "5001:80"
    depends_on:
      - backend

  frontend-angular:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    container_name: frontend-container-angular
    ports:
      - "5002:80"
    depends_on:
      - backend

volumes:
  db_data:
