version: '3.8'

services:
  shoppingdb-container:
    image: postgres:17
    container_name: shoppingdb-container
    restart: always
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend-container
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - shoppingdb-container

  frontend-react:
    build: ./frontend-react
    container_name: frontend-react-container
    restart: always
    ports:
      - "${FRONTEND_REACT_PORT}:80"
    depends_on:
      - backend

  frontend-angular:
    build: ./frontend-angular
    container_name: frontend-angular-container
    restart: always
    ports:
      - "${FRONTEND_ANGULAR_PORT}:80"
    depends_on:
      - backend

volumes:
  postgres_data:
