apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b
  namespace: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-b
  template:
    metadata:
      labels:
        app: backend-b
    spec:
      containers:
        - name: backend
          image: philthygpt/backend:latest
          env:
            - name: DB_HOST
              value: db-b
            - name: DB_USER
              value: hse24
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: shoppingdb_b
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-b
  namespace: shopping-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend-b
  type: ClusterIP
