apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-angular
  namespace: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-angular
  template:
    metadata:
      labels:
        app: frontend-angular
    spec:
      containers:
        - name: frontend-angular
          image: philthygpt/frontend-angular:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-angular
  namespace: shopping-app
spec:
  type: NodePort
  selector:
    app: frontend-angular
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002  # Fester Port für den Zugriff über Minikube
