apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react
  namespace: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
        - name: frontend-react
          image: philthygpt/frontend-react:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-react
  namespace: shopping-app
spec:
  type: NodePort
  selector:
    app: frontend-react
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
